# Generated by Django 5.1.2 on 2024-11-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='order_completed',
            field=models.BooleanField(default=False),
        ),
    ]
